/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const vaultItems = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        cascadeDelete: false,
        collectionId: "pbc_2726680096",
        hidden: false,
        id: "relation_agent",
        maxSelect: 1,
        minSelect: 0,
        name: "agent",
        presentable: false,
        required: false,
        system: false,
        type: "relation",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_handle",
        max: 0,
        min: 0,
        name: "handle",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "select_type",
        maxSelect: 1,
        name: "type",
        presentable: false,
        required: true,
        system: false,
        type: "select",
        values: ["api_key", "username_password", "oauth_refresh", "secret"],
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_service",
        max: 0,
        min: 0,
        name: "service",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_username",
        max: 0,
        min: 0,
        name: "username",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_secretCiphertext",
        max: 0,
        min: 0,
        name: "secretCiphertext",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_secretIv",
        max: 0,
        min: 0,
        name: "secretIv",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_secretTag",
        max: 0,
        min: 0,
        name: "secretTag",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "number_keyVersion",
        max: null,
        min: null,
        name: "keyVersion",
        onlyInt: true,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        hidden: false,
        id: "select_exposureMode",
        maxSelect: 1,
        name: "exposureMode",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["inject_only", "revealable"],
      },
      {
        hidden: false,
        id: "bool_disabled",
        name: "disabled",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_notes",
        max: 0,
        min: 0,
        name: "notes",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "json_tags",
        maxSize: 2000000,
        name: "tags",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        hidden: false,
        id: "date_lastUsedAt",
        max: "",
        min: "",
        name: "lastUsedAt",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_lastRotatedAt",
        max: "",
        min: "",
        name: "lastRotatedAt",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_8015040701",
    indexes: ["CREATE UNIQUE INDEX `idx_agent_handle_pbc_8015040701` ON `vault_items` (`agent`, `handle`)"],
    listRule: null,
    name: "vault_items",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  const vaultAgentTokens = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        cascadeDelete: false,
        collectionId: "pbc_2726680096",
        hidden: false,
        id: "relation_agent",
        maxSelect: 1,
        minSelect: 0,
        name: "agent",
        presentable: false,
        required: true,
        system: false,
        type: "relation",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_label",
        max: 0,
        min: 0,
        name: "label",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_tokenHash",
        max: 0,
        min: 0,
        name: "tokenHash",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_tokenPrefix",
        max: 0,
        min: 0,
        name: "tokenPrefix",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "bool_disabled",
        name: "disabled",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "date_lastUsedAt",
        max: "",
        min: "",
        name: "lastUsedAt",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_8015040702",
    indexes: [
      "CREATE UNIQUE INDEX `idx_tokenPrefix_pbc_8015040702` ON `vault_agent_tokens` (`tokenPrefix`)",
      "CREATE INDEX `idx_agent_pbc_8015040702` ON `vault_agent_tokens` (`agent`)",
    ],
    listRule: null,
    name: "vault_agent_tokens",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  const vaultAudit = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        hidden: false,
        id: "date_ts",
        max: "",
        min: "",
        name: "ts",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "select_actorType",
        maxSelect: 1,
        name: "actorType",
        presentable: false,
        required: true,
        system: false,
        type: "select",
        values: ["human", "agent"],
      },
      {
        cascadeDelete: false,
        collectionId: "pbc_2726680096",
        hidden: false,
        id: "relation_agent",
        maxSelect: 1,
        minSelect: 0,
        name: "agent",
        presentable: false,
        required: false,
        system: false,
        type: "relation",
      },
      {
        cascadeDelete: false,
        collectionId: "pbc_8015040701",
        hidden: false,
        id: "relation_vaultItem",
        maxSelect: 1,
        minSelect: 0,
        name: "vaultItem",
        presentable: false,
        required: false,
        system: false,
        type: "relation",
      },
      {
        hidden: false,
        id: "select_action",
        maxSelect: 1,
        name: "action",
        presentable: false,
        required: true,
        system: false,
        type: "select",
        values: ["create", "update", "rotate", "disable", "enable", "delete", "resolve", "reveal"],
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_sessionKey",
        max: 0,
        min: 0,
        name: "sessionKey",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_toolName",
        max: 0,
        min: 0,
        name: "toolName",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "select_status",
        maxSelect: 1,
        name: "status",
        presentable: false,
        required: true,
        system: false,
        type: "select",
        values: ["ok", "deny", "error"],
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_error",
        max: 0,
        min: 0,
        name: "error",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "json_meta",
        maxSize: 2000000,
        name: "meta",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
    ],
    id: "pbc_8015040703",
    indexes: [
      "CREATE INDEX `idx_agent_ts_pbc_8015040703` ON `vault_audit` (`agent`, `ts`)",
      "CREATE INDEX `idx_ts_pbc_8015040703` ON `vault_audit` (`ts`)",
    ],
    listRule: null,
    name: "vault_audit",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  app.save(vaultItems);
  app.save(vaultAgentTokens);
  return app.save(vaultAudit);
}, (app) => {
  const audit = app.findCollectionByNameOrId("pbc_8015040703");
  app.delete(audit);

  const tokens = app.findCollectionByNameOrId("pbc_8015040702");
  app.delete(tokens);

  const items = app.findCollectionByNameOrId("pbc_8015040701");
  return app.delete(items);
});

