/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        hidden: false,
        id: "date_usage_ts",
        max: "",
        min: "",
        name: "ts",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_usage_source",
        max: 0,
        min: 0,
        name: "source",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_usage_sessionKey",
        max: 0,
        min: 0,
        name: "sessionKey",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_usage_agentId",
        max: 0,
        min: 0,
        name: "agentId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_usage_taskId",
        max: 0,
        min: 0,
        name: "taskId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_usage_projectId",
        max: 0,
        min: 0,
        name: "projectId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_usage_model",
        max: 0,
        min: 0,
        name: "model",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "number_usage_input",
        max: null,
        min: null,
        name: "inputTokens",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        hidden: false,
        id: "number_usage_output",
        max: null,
        min: null,
        name: "outputTokens",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        hidden: false,
        id: "number_usage_used",
        max: null,
        min: null,
        name: "tokensUsed",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        hidden: false,
        id: "number_usage_max",
        max: null,
        min: null,
        name: "tokensMax",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        hidden: false,
        id: "number_usage_pct",
        max: null,
        min: null,
        name: "tokensPct",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        hidden: false,
        id: "number_usage_cost",
        max: null,
        min: null,
        name: "estimatedCostUsd",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        hidden: false,
        id: "date_usage_createdAt",
        max: "",
        min: "",
        name: "createdAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_usage_updatedAt",
        max: "",
        min: "",
        name: "updatedAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_9051300003",
    indexes: [
      "CREATE INDEX `idx_ts_usage_events` ON `usage_events` (`ts`)",
      "CREATE INDEX `idx_project_ts_usage_events` ON `usage_events` (`projectId`, `ts`)",
      "CREATE INDEX `idx_task_ts_usage_events` ON `usage_events` (`taskId`, `ts`)",
      "CREATE INDEX `idx_agent_ts_usage_events` ON `usage_events` (`agentId`, `ts`)",
      "CREATE INDEX `idx_session_ts_usage_events` ON `usage_events` (`sessionKey`, `ts`)",
    ],
    listRule: null,
    name: "usage_events",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_9051300003");
  return app.delete(collection);
});

