/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_taskdep_blocked",
        max: 0,
        min: 0,
        name: "blockedTaskId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_taskdep_depends",
        max: 0,
        min: 0,
        name: "dependsOnTaskId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_taskdep_reason",
        max: 0,
        min: 0,
        name: "reason",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "select_taskdep_kind",
        maxSelect: 1,
        name: "kind",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["blocks"],
      },
      {
        hidden: false,
        id: "date_taskdep_createdAt",
        max: "",
        min: "",
        name: "createdAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_taskdep_updatedAt",
        max: "",
        min: "",
        name: "updatedAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_9051300002",
    indexes: [
      "CREATE UNIQUE INDEX `idx_unique_task_dependency` ON `task_dependencies` (`blockedTaskId`, `dependsOnTaskId`)",
      "CREATE INDEX `idx_blocked_task_dependencies` ON `task_dependencies` (`blockedTaskId`)",
      "CREATE INDEX `idx_depends_task_dependencies` ON `task_dependencies` (`dependsOnTaskId`)",
    ],
    listRule: null,
    name: "task_dependencies",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_9051300002");
  return app.delete(collection);
});

