/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workspace_name",
        max: 0,
        min: 0,
        name: "name",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workspace_slug",
        max: 0,
        min: 0,
        name: "slug",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        convertURLs: false,
        hidden: false,
        id: "editor_workspace_description",
        maxSize: 500000,
        name: "description",
        presentable: false,
        required: false,
        system: false,
        type: "editor",
      },
      {
        hidden: false,
        id: "bool_workspace_archived",
        name: "archived",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "date_workspace_createdAt",
        max: "",
        min: "",
        name: "createdAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_workspace_updatedAt",
        max: "",
        min: "",
        name: "updatedAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_9051300010",
    indexes: [
      "CREATE UNIQUE INDEX `idx_slug_workspaces` ON `workspaces` (`slug`) WHERE `slug` != ''",
      "CREATE INDEX `idx_archived_workspaces` ON `workspaces` (`archived`)",
    ],
    listRule: null,
    name: "workspaces",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_9051300010");
  return app.delete(collection);
});
