/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_wfa_run_id",
        max: 0,
        min: 0,
        name: "runId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_wfa_workflow_id",
        max: 0,
        min: 0,
        name: "workflowId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_wfa_task_id",
        max: 0,
        min: 0,
        name: "taskId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "number_wfa_step_index",
        max: null,
        min: null,
        name: "stepIndex",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_wfa_title",
        max: 0,
        min: 0,
        name: "title",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        convertURLs: false,
        hidden: false,
        id: "editor_wfa_instructions",
        maxSize: 500000,
        name: "instructions",
        presentable: false,
        required: false,
        system: false,
        type: "editor",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_wfa_reviewer_agent_id",
        max: 0,
        min: 0,
        name: "reviewerAgentId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "select_wfa_status",
        maxSelect: 1,
        name: "status",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["pending", "approved", "rejected"],
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_wfa_decision_note",
        max: 0,
        min: 0,
        name: "decisionNote",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_wfa_decided_by",
        max: 0,
        min: 0,
        name: "decidedBy",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "date_wfa_decided_at",
        max: "",
        min: "",
        name: "decidedAt",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_wfa_created_at",
        max: "",
        min: "",
        name: "createdAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_wfa_updated_at",
        max: "",
        min: "",
        name: "updatedAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_9051300005",
    indexes: [
      "CREATE INDEX `idx_runId_workflow_step_approvals` ON `workflow_step_approvals` (`runId`)",
      "CREATE INDEX `idx_run_step_workflow_step_approvals` ON `workflow_step_approvals` (`runId`, `stepIndex`)",
      "CREATE INDEX `idx_status_workflow_step_approvals` ON `workflow_step_approvals` (`status`)",
    ],
    listRule: null,
    name: "workflow_step_approvals",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_9051300005");
  return app.delete(collection);
});

