/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_triggers_workflowId",
        max: 0,
        min: 0,
        name: "workflowId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "bool_workflow_triggers_enabled",
        name: "enabled",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "select_workflow_triggers_event",
        maxSelect: 1,
        name: "event",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["task_status_to"],
      },
      {
        hidden: false,
        id: "select_workflow_triggers_statusTo",
        maxSelect: 1,
        name: "statusTo",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["inbox", "assigned", "in_progress", "review", "done", "blocked"],
      },
      {
        hidden: false,
        id: "json_workflow_triggers_labelsAny",
        maxSize: 2000000,
        name: "labelsAny",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_triggers_sessionKey",
        max: 0,
        min: 0,
        name: "sessionKey",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "json_workflow_triggers_vars",
        maxSize: 2000000,
        name: "vars",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        hidden: false,
        id: "date_workflow_triggers_createdAt",
        max: "",
        min: "",
        name: "createdAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_workflow_triggers_updatedAt",
        max: "",
        min: "",
        name: "updatedAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_9051200004",
    indexes: [
      "CREATE INDEX `idx_workflowId_workflow_triggers` ON `workflow_triggers` (`workflowId`)",
      "CREATE INDEX `idx_enabled_statusTo_workflow_triggers` ON `workflow_triggers` (`enabled`, `statusTo`)",
    ],
    listRule: null,
    name: "workflow_triggers",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_9051200004");
  return app.delete(collection);
});

