/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_runs_workflowId",
        max: 0,
        min: 0,
        name: "workflowId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_runs_taskId",
        max: 0,
        min: 0,
        name: "taskId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "select_workflow_runs_status",
        maxSelect: 1,
        name: "status",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["queued", "running", "succeeded", "failed"],
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_runs_sessionKey",
        max: 0,
        min: 0,
        name: "sessionKey",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "json_workflow_runs_vars",
        maxSize: 2000000,
        name: "vars",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        hidden: false,
        id: "json_workflow_runs_result",
        maxSize: 2000000,
        name: "result",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        convertURLs: false,
        hidden: false,
        id: "editor_workflow_runs_log",
        maxSize: 500000,
        name: "log",
        presentable: false,
        required: false,
        system: false,
        type: "editor",
      },
      {
        hidden: false,
        id: "date_workflow_runs_startedAt",
        max: "",
        min: "",
        name: "startedAt",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_workflow_runs_finishedAt",
        max: "",
        min: "",
        name: "finishedAt",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_workflow_runs_createdAt",
        max: "",
        min: "",
        name: "createdAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_workflow_runs_updatedAt",
        max: "",
        min: "",
        name: "updatedAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_9051200002",
    indexes: [
      "CREATE INDEX `idx_workflowId_workflow_runs` ON `workflow_runs` (`workflowId`)",
      "CREATE INDEX `idx_taskId_workflow_runs` ON `workflow_runs` (`taskId`)",
    ],
    listRule: null,
    name: "workflow_runs",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_9051200002");
  return app.delete(collection);
});

