/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_schedules_workflowId",
        max: 0,
        min: 0,
        name: "workflowId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "bool_workflow_schedules_enabled",
        name: "enabled",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "number_workflow_schedules_intervalMinutes",
        max: null,
        min: null,
        name: "intervalMinutes",
        onlyInt: false,
        presentable: false,
        required: false,
        system: false,
        type: "number",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_schedules_taskId",
        max: 0,
        min: 0,
        name: "taskId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_schedules_sessionKey",
        max: 0,
        min: 0,
        name: "sessionKey",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "json_workflow_schedules_vars",
        maxSize: 2000000,
        name: "vars",
        presentable: false,
        required: false,
        system: false,
        type: "json",
      },
      {
        hidden: false,
        id: "bool_workflow_schedules_running",
        name: "running",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_workflow_schedules_runningRunId",
        max: 0,
        min: 0,
        name: "runningRunId",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "date_workflow_schedules_lastRunAt",
        max: "",
        min: "",
        name: "lastRunAt",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_workflow_schedules_nextRunAt",
        max: "",
        min: "",
        name: "nextRunAt",
        presentable: false,
        required: false,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_workflow_schedules_createdAt",
        max: "",
        min: "",
        name: "createdAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_workflow_schedules_updatedAt",
        max: "",
        min: "",
        name: "updatedAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_9051200003",
    indexes: [
      "CREATE INDEX `idx_workflowId_workflow_schedules` ON `workflow_schedules` (`workflowId`)",
      "CREATE INDEX `idx_enabled_nextRunAt_workflow_schedules` ON `workflow_schedules` (`enabled`, `nextRunAt`)",
    ],
    listRule: null,
    name: "workflow_schedules",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_9051200003");
  return app.delete(collection);
});

