/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: null,
    deleteRule: null,
    fields: [
      {
        autogeneratePattern: "[a-z0-9]{15}",
        hidden: false,
        id: "text3208210256",
        max: 15,
        min: 15,
        name: "id",
        pattern: "^[a-z0-9]+$",
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_project_name",
        max: 0,
        min: 0,
        name: "name",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: "text",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_project_slug",
        max: 0,
        min: 0,
        name: "slug",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        convertURLs: false,
        hidden: false,
        id: "editor_project_description",
        maxSize: 500000,
        name: "description",
        presentable: false,
        required: false,
        system: false,
        type: "editor",
      },
      {
        autogeneratePattern: "",
        hidden: false,
        id: "text_project_color",
        max: 0,
        min: 0,
        name: "color",
        pattern: "",
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: "text",
      },
      {
        hidden: false,
        id: "select_project_mode",
        maxSelect: 1,
        name: "mode",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["manual", "supervised", "autopilot"],
      },
      {
        hidden: false,
        id: "select_project_status",
        maxSelect: 1,
        name: "status",
        presentable: false,
        required: false,
        system: false,
        type: "select",
        values: ["active", "paused", "archived"],
      },
      {
        hidden: false,
        id: "bool_project_archived",
        name: "archived",
        presentable: false,
        required: false,
        system: false,
        type: "bool",
      },
      {
        hidden: false,
        id: "date_project_createdAt",
        max: "",
        min: "",
        name: "createdAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
      {
        hidden: false,
        id: "date_project_updatedAt",
        max: "",
        min: "",
        name: "updatedAt",
        presentable: false,
        required: true,
        system: false,
        type: "date",
      },
    ],
    id: "pbc_9051300001",
    indexes: [
      "CREATE UNIQUE INDEX `idx_slug_projects` ON `projects` (`slug`) WHERE `slug` != ''",
      "CREATE INDEX `idx_archived_projects` ON `projects` (`archived`)",
    ],
    listRule: null,
    name: "projects",
    system: false,
    type: "base",
    updateRule: null,
    viewRule: null,
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_9051300001");
  return app.delete(collection);
});

