import { NextRequest, NextResponse } from 'next/server';
import { pbFetch } from '@/lib/pbServer';

export const runtime = 'nodejs';

function safeString(value: unknown) {
  return typeof value === 'string' ? value.trim() : '';
}

function normalizeStatus(value: unknown) {
  const status = safeString(value).toLowerCase();
  if (status === 'on_track' || status === 'at_risk' || status === 'off_track') return status;
  return '';
}

export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const q = url.searchParams.toString();
  const data = await pbFetch(`/api/collections/project_status_updates/records?${q}`);
  return NextResponse.json(data);
}

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => ({}));
  const now = new Date().toISOString();
  const projectId = safeString(body?.projectId);
  if (!projectId) return NextResponse.json({ ok: false, error: 'projectId required' }, { status: 400 });
  const status = normalizeStatus(body?.status) || 'on_track';
  const summary = safeString(body?.summary);
  if (!summary) return NextResponse.json({ ok: false, error: 'summary required' }, { status: 400 });

  const payload = {
    projectId,
    status,
    summary,
    highlights: safeString(body?.highlights),
    risks: safeString(body?.risks),
    nextSteps: safeString(body?.nextSteps),
    autoGenerated: Boolean(body?.autoGenerated ?? false),
    createdAt: now,
    updatedAt: now,
  };

  const created = await pbFetch('/api/collections/project_status_updates/records', {
    method: 'POST',
    body: payload,
  });
  return NextResponse.json(created);
}
