export type TaskStatus = 'inbox' | 'assigned' | 'in_progress' | 'review' | 'done' | 'blocked';

export type ReviewChecklistItem = { id: string; label: string; done: boolean };
export type ReviewChecklist = { version: 1; items: ReviewChecklistItem[] };

export type OpenClawTaskPolicy = {
  // Delivery controls for worker -> OpenClaw notification sends.
  openclaw?: {
    mute?: boolean;
    // Suppress sends once the per-task OpenClaw session reaches these limits.
    maxTokensPct?: number;
    maxTokensUsed?: number;
    // Per (agent, task) send cap enforced by the worker for notifications.
    maxSendsPerHour?: number;
  };
};

export type TaskRecurrenceFrequency = 'hourly' | 'daily' | 'weekly' | 'monthly';
export type TaskRecurrenceMode = 'after_completion';

export type TaskRecurrence = {
  version: 1;
  frequency: TaskRecurrenceFrequency;
  interval: number;
  weekdays?: number[];
  monthday?: number;
  mode?: TaskRecurrenceMode;
};

export type Task = {
  id: string;
  projectId?: string;
  title: string;
  description?: string;
  context?: string;
  // Optional Vault credential handle (or hint) associated with the task.
  // This must never contain plaintext secrets.
  vaultItem?: string;
  status: TaskStatus;
  archived?: boolean;
  priority?: string;
  aiEffort?: string;
  aiThinking?: string;
  aiModelTier?: string;
  // Optional explicit OpenClaw model key/alias override for this task.
  aiModel?: string;
  assigneeIds?: string[];
  labels?: string[];
  requiredNodeId?: string;
  leaseOwnerAgentId?: string;
  leaseExpiresAt?: string;
  attemptCount?: number;
  lastProgressAt?: string;
  maxAutoNudges?: number;
  escalationAgentId?: string;
  createdAt?: string;
  updatedAt?: string;
  startAt?: string;
  dueAt?: string;
  completedAt?: string;
  recurrence?: TaskRecurrence | null;
  recurrenceSeriesId?: string;
  recurrenceFromTaskId?: string;
  recurrenceSpawnedTaskId?: string;
  requiresReview?: boolean;
  // Optional task-level policy knobs (e.g. future tool profile / escalation rules).
  policy?: OpenClawTaskPolicy | unknown;
  // When requiresReview=true, this can enforce a "done" gate and provide deterministic review steps.
  reviewChecklist?: ReviewChecklist | null;
  order?: number;
  subtasksTotal?: number;
  subtasksDone?: number;
};

export type ProjectMode = 'manual' | 'supervised' | 'autopilot';
export type ProjectStatus = 'active' | 'paused' | 'archived';

export type Project = {
  id: string;
  name: string;
  slug?: string;
  workspaceId?: string;
  description?: string;
  color?: string;
  mode?: ProjectMode;
  status?: ProjectStatus;
  dailyBudgetUsd?: number;
  monthlyBudgetUsd?: number;
  budgetWarnPct?: number;
  archived?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type Workspace = {
  id: string;
  name: string;
  slug?: string;
  description?: string;
  archived?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type ProjectStatusLevel = 'on_track' | 'at_risk' | 'off_track';

export type ProjectStatusUpdate = {
  id: string;
  projectId: string;
  status?: ProjectStatusLevel | string;
  summary?: string;
  highlights?: string;
  risks?: string;
  nextSteps?: string;
  autoGenerated?: boolean;
  createdAt?: string;
  updatedAt?: string;
};

export type Agent = {
  id: string;
  displayName?: string;
  role?: string;
  openclawAgentId?: string;
  avatar?: string | string[];
  status?: string;
  currentTaskId?: string;
  lastSeenAt?: string;
  lastWorklogAt?: string;
  modelTier?: string;
  defaultNodeId?: string;
};

export type Activity = {
  id: string;
  type: string;
  summary: string;
  taskId?: string;
  createdAt?: string;
};

export type Message = {
  id: string;
  taskId: string;
  fromAgentId?: string;
  content: string;
  createdAt?: string;
  updatedAt?: string;
};

export type DocumentRecord = {
  id: string;
  taskId?: string;
  title: string;
  content?: string;
  type?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type TaskFile = {
  id: string;
  taskId: string;
  title?: string;
  file?: string | string[];
  shareToken: string;
  createdAt?: string;
  updatedAt?: string;
};

export type NodeRecord = {
  id: string;
  nodeId?: string;
  displayName?: string;
  paired?: boolean;
  lastSeenAt?: string;
  os?: string;
  arch?: string;
  capabilities?: unknown;
  execPolicy?: string;
  allowlistSummary?: string;
};

export type PBList<T> = {
  items: T[];
  page: number;
  perPage: number;
  totalItems: number;
  totalPages: number;
};

export type NotificationKind =
  | 'generic'
  | 'assigned'
  | 'mentioned'
  | 'nudge'
  | 'escalation'
  | 'workflow_failed'
  | 'review_requested'
  | 'budget_exceeded'
  | 'incident';

export type NotificationRecord = {
  id: string;
  toAgentId: string;
  taskId?: string;
  content: string;
  kind?: NotificationKind | string;
  title?: string;
  url?: string;
  delivered?: boolean;
  deliveredAt?: string;
  readAt?: string;
  created?: string;
  updated?: string;
};

export type TaskDependency = {
  id: string;
  blockedTaskId: string;
  dependsOnTaskId: string;
  reason?: string;
  kind?: 'blocks' | string;
  createdAt?: string;
  updatedAt?: string;
  blockedTask?: Task | null;
  dependsOnTask?: Task | null;
};

export type TaskView = {
  id: string;
  name: string;
  description?: string;
  filters?: {
    projectId?: string;
    status?: TaskStatus | '';
    assignee?: string;
    priority?: string;
    q?: string;
    sort?: string;
  } | null;
  createdAt?: string;
  updatedAt?: string;
};

export type UsageEvent = {
  id: string;
  ts: string;
  source?: string;
  sessionKey?: string;
  agentId?: string;
  taskId?: string;
  projectId?: string;
  model?: string;
  inputTokens?: number;
  outputTokens?: number;
  tokensUsed?: number;
  tokensMax?: number;
  tokensPct?: number;
  estimatedCostUsd?: number;
  createdAt?: string;
  updatedAt?: string;
};

export type Subtask = {
  id: string;
  taskId: string;
  title: string;
  done?: boolean;
  order?: number;
  assigneeIds?: string[];
  dueAt?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type VaultItemType = 'api_key' | 'username_password' | 'oauth_refresh' | 'secret';
export type VaultExposureMode = 'inject_only' | 'revealable';

export type VaultItem = {
  id: string;
  agent?: string;
  handle: string;
  type: VaultItemType;
  service?: string;
  username?: string;
  exposureMode?: VaultExposureMode;
  disabled?: boolean;
  notes?: string;
  tags?: unknown;
  lastUsedAt?: string;
  lastRotatedAt?: string;
  created?: string;
  updated?: string;
};

export type VaultAgentToken = {
  id: string;
  agent: string;
  label?: string;
  tokenPrefix: string;
  disabled?: boolean;
  lastUsedAt?: string;
  created?: string;
  updated?: string;
};

export type VaultAuditActorType = 'human' | 'agent';
export type VaultAuditAction = 'create' | 'update' | 'rotate' | 'disable' | 'enable' | 'delete' | 'resolve' | 'reveal';
export type VaultAuditStatus = 'ok' | 'deny' | 'error';

export type VaultAudit = {
  id: string;
  ts: string;
  actorType: VaultAuditActorType;
  agent?: string;
  vaultItem?: string;
  action: VaultAuditAction;
  sessionKey?: string;
  toolName?: string;
  status: VaultAuditStatus;
  error?: string;
  meta?: unknown;
  created?: string;
  updated?: string;
};

export type WorkflowKind = 'lobster' | 'manual';
export type Workflow = {
  id: string;
  name: string;
  description?: string;
  kind?: WorkflowKind;
  pipeline?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type WorkflowRunStatus = 'queued' | 'running' | 'succeeded' | 'failed';
export type WorkflowRun = {
  id: string;
  workflowId: string;
  taskId?: string;
  status?: WorkflowRunStatus;
  sessionKey?: string;
  commandId?: string;
  vars?: unknown;
  result?: unknown;
  log?: string;
  startedAt?: string;
  finishedAt?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type WorkflowStepApprovalStatus = 'pending' | 'approved' | 'rejected';
export type WorkflowStepApproval = {
  id: string;
  runId: string;
  workflowId?: string;
  taskId?: string;
  stepIndex?: number;
  title?: string;
  instructions?: string;
  reviewerAgentId?: string;
  status?: WorkflowStepApprovalStatus;
  decisionNote?: string;
  decidedBy?: string;
  decidedAt?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type WorkflowSchedule = {
  id: string;
  workflowId: string;
  enabled?: boolean;
  intervalMinutes?: number;
  taskId?: string;
  sessionKey?: string;
  vars?: unknown;
  running?: boolean;
  runningRunId?: string;
  runningStartedAt?: string;
  lastRunAt?: string;
  nextRunAt?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type WorkflowTriggerEvent = 'task_status_to' | 'task_created' | 'task_due_soon';
export type WorkflowTrigger = {
  id: string;
  workflowId: string;
  enabled?: boolean;
  event?: WorkflowTriggerEvent;
  statusTo?: TaskStatus;
  labelsAny?: string[] | unknown;
  projectId?: string;
  priority?: string;
  assigneeId?: string;
  dueWithinMinutes?: number;
  actions?: unknown;
  sessionKey?: string;
  vars?: unknown;
  createdAt?: string;
  updatedAt?: string;
};
